name: Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Install Dependencies
        run: npm install

      - name: Install Theme Dependencies
        run: npm install --prefix themes/next

      - name: Verify Theme Directory
        run: ls -la themes/next/layout

      - name: Build Hexo
        run: npm run build
      
      ## Add .nojekyll to prevent GitHub Pages from ignoring files that start with an underscore
      - name: Add .nojekyll
        run: touch public/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4